---
- name: "Configurar NGINX proxy"
  hosts: localhost
  gather_facts: false
  vars:
    project_root: "{{ playbook_dir }}/.."
    nginx_conf_host: "{{ project_root }}/host_volumes/nginx_conf"
    proxy_root: "{{ project_root }}/host_volumes/proxy"

    nginx_container: "nginx-proxy-dev"

    app1_root: "{{ project_root }}/host_volumes/app1/"
    app2_root: "{{ project_root }}/host_volumes/app2/"
    app3_root: "{{ project_root }}/host_volumes/app3/"

  tasks:
    - name: Crear directorios
      ansible.builtin.file:
        path: "{{item}}"
        state: directory
        mode: "0755"
      loop:
        - "{{ nginx_conf_host }}"
        - "{{ proxy_root }}"
        - "{{ app1_root }}"
        - "{{ app2_root }}"
        - "{{ app3_root }}"

    - name: "Copiar proxy"
      ansible.builtin.copy:
        src: "../files/proxy/index.html"
        dest: "{{proxy_root}}/index.html"
        mode: '0644'

    - name: "Copiar app1"
      ansible.builtin.copy:
        src: "../files/app1/index.html"
        dest: "{{app1_root}}/index.html"
        mode: '0644'

    - name: "Copiar app2"
      ansible.builtin.copy:
        src: "../files/app2/index.html"
        dest: "{{app2_root}}/index.html"
        mode: '0644'

    - name: "Copiar app3"
      ansible.builtin.copy:
        src: "../files/app3/index.html"
        dest: "{{app3_root}}/index.html"
        mode: '0644'

    - name: Copiar la api
      ansible.builtin.copy:
        src: "../templates/nginx.conf"
        dest: "{{nginx_conf_host}}/default.conf"
        mode: '0644'

    - name: Intentar recargar nginx
      ansible.builtin.command: >
        docker exec {{nginx_container}} nginx -s reload
      register: reload_result
      changed_when: reload_result.rc == 0
      failed_when: false
    
    - name: Reiniciar contenedor
      ansible.builtin.command: >
        docker restart {{nginx_container}}
      when: reload_result.rc == 0
      